name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUNDLE_WITHOUT: "development"

jobs:
  test:
    name: "test / ${{ matrix.ruby }}"

    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        ruby: [ ruby-3.0, ruby-3.1, ruby-3.2, ruby-3.3 ]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - run: bundle exec rake test

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v3
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

  # See: https://github.com/orgs/community/discussions/26822#discussioncomment-3305794
  test-finale:
    name: "test"

    runs-on: ubuntu-latest
    if: ${{ always() }}

    needs: [test]

    steps:
      - run: test "success" = "${{ needs.test.result }}"

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby-3.2
          bundler-cache: true

      - run: bundle exec rake lint
